### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by jgravois** [hypermodules/hypermodul.es#11]
?

![screenshot 2017-02-02 10 00 53](https://cloud.githubusercontent.com/assets/3011734/22561767/8a1b505a-e92e-11e6-99f1-925c9e0d706c.png)

**Comment by bcomnes** [comment]
Ah what the shit.

**Comment by bcomnes** [comment]
Looks like netlify is having issues: 
![screen shot 2017-02-02 at 10 03 12 am](https://cloud.githubusercontent.com/assets/166301/22561825/dacb6b3e-e92e-11e6-8d0e-2ef7d2b82506.png)

**Comment by bcomnes** [comment]
There isn't much on the site yet tbh.  Mainly just a placeholder for the time being.  It has parity to markdown files in the repo, which are just links to repos right now.

**Comment by jgravois** [comment]
thats good enough to me.  hello from redlands!

**Comment by bcomnes** [comment]
I was thinking of doing some kind of FAQ thingy about hypermodular development though

**Comment by bcomnes** [comment]
ok its back
