### ISSUE TITLE
Section link to FAQ

### ISSUE THREAD

**Issue by strugee** [hypermodules/hypermodul.es#37]
I'd like to be able to link directly to the FAQ with e.g. https://www.hypermodul.es/#faq

**Comment by bcomnes** [comment]
Agreed!  I'll add an ID.  @strugee If you have time, it would be super helpful to add https://github.com/Flet/markdown-it-github-headings to https://github.com/hypermodules/sitedown.  That way headers get auto-id'd. See https://github.com/hypermodules/sitedown for more details

**Comment by bcomnes** [comment]
Actually, that looks to be a requirement to ID the FAQ since thats actually a markdown header.  In the meantime, https://www.hypermodul.es/#hypermodular is linkable.
