### ISSUE TITLE
Hypermodules is dead long live hypermodules

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hypermodul.es#81]
Hey all,

Hypermodules is dead! We did some really fun work together here and even made some super useful things along the way that are alive and well. But the underlying project of Hyperamp is dead and in some ways the open open source org model ended up muddling maintainership and sort of added a layer of hesitation around individual contributions. That said, I have no regrets, and had a ton of fun working on everything here and continue to enjoyed many doodads we built here. 

I was thinking of a way to wrap things up and had a few ideas.

a) Leave things be. Archive old noisy stuff we don't care about, keep chipping away on the repos that we still use today. Low effort, and acknowledging this I think might remove any feelings that I am somehow holding other peoples work hostage. 

b) Offer to return active repos back to their originators, maintaining contributor status unless otherwise desired, and hypermodules specific repos would just continue to live in the org as is, possibly archived, as a tomb of our success. This would be a bit more work but something I'm willing to help out with. 

- https://github.com/hypermodules/changelog-parser -> ungoldman
- https://github.com/hypermodules/gh-release -> ungoldman
- https://github.com/hypermodules/gh-release-assets/graphs/contributors -> paulcpederson
- https://github.com/hypermodules/format-duration -> ungoldman or leave here
- https://github.com/hypermodules/hyperamp -> leave in hypermodules
- https://github.com/hypermodules/sitedown -> ungoldman
- https://github.com/hypermodules/entypo -> leave here
- https://github.com/hypermodules/level-idx -> bcomnes
- https://github.com/hypermodules/hypermodul.es -> leave here
- https://github.com/hypermodules/level-auto-index -> bcomnes
- https://github.com/hypermodules/level-hookdown -> bcomnes
- https://github.com/hypermodules/dti leave here archive
- https://github.com/hypermodules/gh-release-test leave here or ungoldman
- https://github.com/hypermodules/stability-badges leave here/archive 
- https://github.com/hypermodules/irc.hypermodul.es leave here archive
- https://github.com/hypermodules/signalhub.decent.digital leave here archive
- https://github.com/hypermodules/browser-audio-player archive/delete
- https://github.com/hypermodules/electron-audio-player archive/delete
- https://github.com/hypermodules/abstract-audio-player archive/delete
- https://github.com/hypermodules/electron-ipc-log leave here/archive or ungoldman
- https://github.com/hypermodules/electron-repl archive here or ungoldman
- https://github.com/hypermodules/yt-pip ungoldman
- https://github.com/hypermodules/music-library archive here
- https://github.com/hypermodules/changelog-init archive here
- https://github.com/hypermodules/hypermodules.github.io archive/delete

c) Something else?

As time goes on, I've come to prefer clear ownership over packages, and while I like the idea of being able to maintain the understanding individual ownership even inside of an org, moving packages back into individual accounts in some ways clarifies this understanding among contributors but also outside consumers. Also, in scenarios when the underlying org becomes stale, packages that still have use are freed from the burden of being in a stale org.

Thoughts @blahah @jgravois @nikolaswise @paulcpederson @ungoldman @zeke ?

**Comment by ungoldman** [comment]
I have been thinking along similar lines! It was a great project but I think we've all moved on to other things for quite some time now. It would be good to clean house, archive what needs archiving, and transfer out active projects to those willing to assume ownership and continue maintaining them.

I am fine with resuming ownership of the repos I authored and archiving the old/abandoned stuff that no one wants to claim. Contributor access _should_ transfer for all the active repos that others have contributed to over the years (gh-release & changelog-parser in particular are still actively in use in the wild). If not I'll make sure to add all those that had access before.

Here's a list of repos I'll transfer to myself if everyone's fine with it:

- [x] gh-release
- [x] gh-release-test
- [x] changelog-parser
- [x] sitedown
- [x] format-duration
- [x] electron-ipc-log
- [x] electron-repl
- [x] yt-pip

If @paulcpederson has the bandwidth/desire to own & maintain `gh-release-assets` I am happy to transfer it to him, otherwise I'm okay taking that over as well.

Thanks all for the many contributions and for being part of this experiment.

May your works proliferate! Best of luck to all.

**Comment by jgravois** [comment]
i'm happy to chime in when there's activity regardless of where the repos relocate and its definitely good stewardship to say goodnight to the rest officially. 🛏️

**Comment by bcomnes** [comment]
@ungoldman feel free to snag stuff from css-pkg too or leave them there whatever you prefer. That was a tangential project to hypermodules with similar goals in mind.

**Comment by bcomnes** [comment]
Good to see you all ❤️

Just to fill people in on what hypermodules was/is for the last few years, the LLC I formed for software signing just turned into a billing endpoint for me for small individual contracts I did over the years. I plan on letting it sunset end of 2022.

**Comment by ungoldman** [comment]
I think I will snag style.css and archive top-bar.css

**Comment by paulcpederson** [comment]
Wow end of an era. I guess the real hypermodules were the friends we made along the way.

> If @paulcpederson has the bandwidth/desire to own & maintain gh-release-assets I am happy to transfer it to him, otherwise I'm okay taking that over as well.

@ungoldman I am probably not the right person to own this as I haven't added anything since 2015. I think @bcomnes probably is more familiar with it as this point...

**Comment by bcomnes** [comment]
I still use gh-release a ton and plan on helping maintain it but the release asset portion should live near or in it.

**Comment by ungoldman** [comment]
Alright it sounds like we have a quorum and there is enough consensus to move forward. Unless there are any objections I'll start transferring ownership of repos I listed above (+ gh-release-assets) in a couple of hours.

**Comment by bcomnes** [comment]
Sounds good, let me know if you want to delegate any tasks around integrations.

**Comment by ungoldman** [comment]
@bcomnes which integrations do we need to worry about?

The two most active / used repos, gh-release & changelog-parser, both use gh actions so I _think_ should continue to work w/o modification.

Are there integrations besides test/CI stuff? I see some old webhooks in gh-release but they all seem to be defunct & safe to delete:

---

<img width="802" alt="Screen Shot 2022-03-11 at 10 33 42 AM" src="https://user-images.githubusercontent.com/427322/157930729-607cc32b-4e08-485c-b61b-a23714e81a57.png">

---

I'll need to figure out how much time I want to spend on the project sites (like https://hypermodules.github.io/gh-release/) but for now I think it's okay to just rebuild the gh pages under my user namespace and fix links.

**Comment by bcomnes** [comment]
I think websites are the only main thing that needs tweaking. Otherwise any remaining travis should just be migrated to gh-actions

**Comment by ungoldman** [comment]
All help is welcome 🙇

**Comment by zeke** [comment]
Hey party people. Happy to see this thoughtful consideration of what to do with this org and the projects within it. That in itself is pretty rare. 💛 

I have used and contributed to some of the projects in this org over the years, but I don't think I'm involved enough with any of them to consider myself an owner. Let me know if there's anything I can do to help the effort!

**Comment by zeke** [comment]
> I still use gh-release

I do too. Pretty sure this is the only remaining project in this org that I actively depend on.

**Comment by ungoldman** [comment]
I have transferred all the easy ones (format-duration, electron-ipc-log, electron-repl, yt-pip). Will work on the rest that require a little more care later today.

**Comment by ungoldman** [comment]
All that's left for me is `gh-release` and `gh-release-assets`, holding off on those until we resolve a curious package squatting mystery for `gh-release-test` (see https://github.com/ungoldman/gh-release-test/issues/2 if you're curious).

@bcomnes: I'm going to archive & deprecate these repos tomorrow:

- [x] https://github.com/hypermodules/stability-badges
- ~https://github.com/hypermodules/browser-audio-player~
- ~https://github.com/hypermodules/electron-audio-player~
- ~https://github.com/hypermodules/abstract-audio-player~
- ~https://github.com/hypermodules/music-library~
- [x] https://github.com/hypermodules/changelog-init

Edit: I don't have access to *-player and music-library modules on npm so I'll leave those to @bcomnes.

**Comment by bcomnes** [comment]
Sounds good 👍 thanks for finishing that

**Comment by bcomnes** [comment]
I just recalled we also need to move the gh-release oauth app to ungoldman too.

**Comment by ungoldman** [comment]
@bcomnes there is a gh-release oauth application? I'm not aware of that

**Comment by bcomnes** [comment]
You can still use personal access tokens with it, but ghauth was updated to support the device oauth flow. See README in https://github.com/rvagg/ghauth for more deets. I can transfer it to you today. Basically gives you a clientId token that the CLI ships.

**Comment by ungoldman** [comment]
@bcomnes is there any chance this will reset all the auth tokens for gh-release users?

**Comment by bcomnes** [comment]
I don't think so.

**Comment by bcomnes** [comment]
Crossing my eyes to understand what this means:
![Screen Shot 2022-03-14 at 1 10 16 PM](https://user-images.githubusercontent.com/166301/158253046-eb9ad857-ab26-45bb-8e28-a37141827de9.png)

**Comment by ungoldman** [comment]
@bcomnes I see it now (https://github.com/organizations/hypermodules/settings/applications/1350509). Thought there was some kind of secret oauth web app hosted somewhere that I had totally missed. 😂 I think I can do the transfer myself when I'm also transferring the gh-release repo itself. Would rather coordinate the two moves and figure everything out in a time block of my choosing if that's alright with you.

**Comment by bcomnes** [comment]
Go for it if you feel comfortable doing it.

**Comment by blahah** [comment]
Hi all, just echoing @jgravois @paulcpederson and @zeke to say that I appreciate the conscientious approach to stewardship and community.

I don't think I've contributed enough to any of these projects to merit being included in decision-making. If I'm wrong about that I'm happy to be asked, or to be assigned tasks that I've forgotten. Otherwise, I hope to cross paths with you all again soon 💜

Life is hypermodular. Long live hypermodularity

**Comment by zeke** [comment]
Hi @blahah! I recognize your avatar, but not your handle. Did you change it? 🤔

**Comment by ungoldman** [comment]
FYI transferring ownership of the OAuth App now, then doing a patch update & release for gh-release to update links on npm & test that there was no disruption with the OAuth device flow setup.

**Comment by ungoldman** [comment]
✅ it worked

```
~/dev/github/gh-release (master) ∴ npm run release

> gh-release@6.0.2 release
> ./bin/cli.js && npm publish

  Authorize with Github by opening this URL in a browser:

    https://github.com/login/device

  and enter the following User Code:
  (or press ⏎ to enter a personal access token)

✔ Device flow complete.  Manage at https://github.com/settings/connections/applications/...
✔ Authorized for ungoldman
Wrote access token to "/Users/ng/Library/Application Support/gh-release/config.json"
```

**Comment by ungoldman** [comment]
I've now transferred ownership for every repo on my end, listing here for the sake of my brain:

- gh-release
- gh-release-assets
- gh-release-test
- changelog-parser
- sitedown
- format-duration
- electron-ipc-log
- electron-repl
- yt-pip

The following repos have also been archived (and deprecated if they're on npm):

- dti
- stability-badges
- changelog-init 
- signalhub.decent.digital
- irc.hypermodul.es

## What's left?

That leaves the following repos to transfer or archive:

### Transfer to @bcomnes

- https://github.com/hypermodules/level-idx
- https://github.com/hypermodules/level-auto-index
- https://github.com/hypermodules/level-hookdown

@bcomnes I'll leave it to you to transfer out the three level-* modules when you have the bandwidth.

### Archive (or delete if desired) & deprecate on npm

- https://github.com/hypermodules/browser-audio-player
- https://github.com/hypermodules/electron-audio-player
- https://github.com/hypermodules/abstract-audio-player
- https://github.com/hypermodules/music-library

@bcomnes I don't have access to these four modules above on npm so I'll leave it to you to deal with them.

### Leave here

- https://github.com/hypermodules/hyperamp
- https://github.com/hypermodules/entypo
- https://github.com/hypermodules/hypermodul.es
- https://github.com/hypermodules/hypermodules.github.io (just a redirect to hypermodul.es)

Are we planning on continuing maintenance for this last group?

**Comment by ungoldman** [comment]
PS: I think I have added everyone who's been active with maintenance on gh-release and changelog-parser in the last few years, if I've missed you and you'd like to be added please let me know!

**Comment by bcomnes** [comment]
Thanks for doing all that work @ungoldman ! I'll review closer when I have a moment.

**Comment by bcomnes** [comment]
I just noticed Alibaba is using gh-release haha https://github.com/alibaba/designable/blob/bd79e5ff9e77d00946a6b141c3aea3e6ba96576c/package.json#L101

**Comment by bcomnes** [comment]
We can close this issue now. Thank you @ungoldman for all that transfer work, I will follow up with a bit more on my end asap.

**Comment by blahah** [comment]
> Hi @blahah! I recognize your avatar, but not your handle. Did you change it? thinking

No, I've had this forgettable handle since 2004 :) If not for the avatar I'd be effectively anonymous.

Thanks again all of you for the exemplary open source stewardship, and for being so consistent in general. I was reminded to revisit this thread because today I started a new experiment and saw some of the handles here in the dependencies I automatically use. Stay hyper ✌🏼
